### ISSUE TITLE
Did you try fit GMM once for all GTs in an image?

### ISSUE THREAD

**Issue by feiyuhuahuo** [kkhoot/PAA#25] opened 2020-12-24 06:07 UTC
Noticed that EM was implemented once per GT. Did you try to fit a total GMM for all candidate anchors in an image?
And by the way, did you try that merge the IoU prediction branch with the box prediction branch, which means you can predict IoU with the box coordinates, thus another branch in the head is not necessary.

**Comment by kkhoot** [comment] 2020-12-25 15:26
Hi @feiyuhuahuo , no, I haven't tried that approach. The GMM in the paper is on 1-dimensional anchor score space, so there is no anchor location information. This means you need to 1) group anchors by location and run GMM per GT or 2) make the anchor score space higher dimensional space and encode anchors' locations. In the paper I chose 1), and so it needs to determine a group of candidate anchors for a certain GT before running EM.
>And by the way, did you try that merge the IoU prediction branch with the box prediction branch, which means you can predict IoU with the box coordinates, thus another branch in the head is not necessary.

I am not sure I get your point. What do you mean by "predict IoU with the box coordinates"? Did you mean merging the box regression head and IoU head into a single conv layer by channel concatenation? It is definitely possible, but it is essentially the same as the current separate two heads.

**Comment by feiyuhuahuo** [comment] 2020-12-28 01:55
1. I'm just thinking that maybe all candidate anchors can be merged into an unified score place, so GMM only need to be done once per image. I can't figure out why location information is needed. Because scores can be seen as a metric to measure whether an anchor should be chosen as a positive sample, if so, grouping anchors by location maybe is not needed.
2. Yes, I mean merging the box regression head and IoU head into a single conv layer by channel concatenation.

**Comment by kkhoot** [comment] 2020-12-28 13:00
Oh now I see your point. Yes, assuming you get anchor scores for all anchors (meaning you already cluster anchors into groups according to their relative locations w.r.t. GTs and compute the losses), you can fit a single GMM for all anchors. I haven't tried this, but I think this could work. But I think this can be less effective than the current approach. This is because some objects might be inherently more difficult to detect for various reasons (e.g., they are seriously occluded or very small, etc.), and best positive anchor scores for these GTs can be significantly lower than those of easier ones. This could lead to a situation where all the anchors for the difficult GT are assigned to be negative samples in the unified GMM.

**Closed as completed** 2021-01-05 07:06 UTC
